services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mechanic_cloud
      TZ: UTC
    command: --default-time-zone='+00:00'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
