server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
<<<<<<< Updated upstream
    url: jdbc:mysql://localhost:3306/mechanic_cloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
=======
    url: jdbc:mysql://localhost:3307/mechanic_cloud
>>>>>>> Stashed changes
    username: root
    password: urubu100
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
