server:
  error:
    include-stracktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mechanic_cloud?useSSL=false
    username: root
    password: urubu100
  jpa:
    hibernate:
      ddl-auto: update